services:
  nx-psql:
    image: postgres:11
    container_name: nx-psql
    ports:
      - ${NX_DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${NX_DB_PWD}
    networks:
      - nuxeo
  nuxeo:
    image: ${NX_IMG}
    container_name: nuxeo
    env_file: .env
    ports:
      - ${NX_PORT}:8080
    networks:
      - nuxeo
    volumes:
      - nuxeo_logs:/var/log/nuxeo
      - nuxeo_temp:/opt/nuxeo/tmp
      - nuxeo_data:/var/lib/nuxeo/data
      - ./data/config:/etc/nuxeo/nuxeo.config
    depends_on:
      - nx-psql
    environment:
      NUXEO_DEV: ${NX_DEV}
      NUXEO_CLID: ${NX_CLID}
      NUXEO_PACKAGES: ${NX_PACKAGES}
      NUXEO_INSTALL_HOTFIX: ${NX_INSTALL_HOTFIX}
      NUXEO_DB_TYPE: ${NX_DB_TYPE}
      NUXEO_DB_NAME: ${NX_DB_NAME}
      NUXEO_DB_USER: ${NX_DB_USER}
      NUXEO_DB_PASSWORD: ${NX_DB_PASSWORD}
      NUXEO_DB_HOST: ${NX_DB_HOST}
      NUXEO_DB_PORT: ${NX_DB_PORT}
networks:
  nuxeo:
    driver: bridge
    name: nuxeo
volumes:
  nuxeo_logs:
  nuxeo_temp:
  nuxeo_data:
